// <auto-generated />
namespace AUCTechnicalTask_AhmedMohammedRabie.DL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addMessageToApply : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMessageToApply));
        
        string IMigrationMetadata.Id
        {
            get { return "202010101229275_add-Message-To-Apply"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
